### PR TITLE
add proposed GSOC doc

### PR DESCRIPTION
**Pull request by klahnakoski**
I hope this can be merged, and then others can update it as they see fit.

### CODE REVIEW

**Comment by klahnakoski** [comment]
@ahal I assume you will preform the merge, after you reviewed.

**Comment by klahnakoski** [comment]
added here: https://wiki.mozilla.org/Community:SummerOfCode19:Brainstorming#2019_Proposed_Project_List

**Comment by klahnakoski** [comment]
@ahal please merge this doc

**Comment by ahal** [comment]
I'll be honest, I don't think this belongs in the repo. That being said since there's a link to it from the wiki and it isn't a big deal I'll merge anyway. Just be aware I'm removing this once the GSoC planning is done :).

**Pull request merged**
