### PR TITLE
Allowing optional filters

### PR DESCRIPTION
**Pull request by MadinaB**
I have been working on this trying to solve this task
given in [here](https://github.com/mozilla/active-data-recipes/pull/69)
```
we'd need to build the query dynamically (depending on whether or not a suite was passed in). This is a problem that ADR could try to solve more generally 
```
This update helps to create query with any optional filters which user can either pass or not pass. 
At first, general query should be created and saved in 'some_query_name'.query file which contains all possible filters.
Then optional filters (getting rid of which will not affect the code) should be saved in optional_arguments and passed to run_query as:
```
run_query('some_query_name', config, optional_arguments=optional_arguments, context)
```
So the code will update the query by deleting filters which rely on arguments which were not passed

### CODE REVIEW

**Comment by MadinaB** [comment]
`adr skipped_tests --from today-week`
 ```                                  
optional_arguments:
['suite', 'platform']

Query before update:
{'from': 'unittest', 'select': [{'aggregate': 'count'}], 'groupby': [{'value': 'result.test'}, {'value': 'run.suite.fullname'}], 'where': {'and': [{'eq': {'run.suite.fullname': {'$eval': 'suite'}}}, {'eq': {'build.platform': {'$eval': 'platform'}}}, {'eq': {'repo.branch.name': 'mozilla-central'}}, {'eq': {'result.status': 'SKIP'}}, {'gte': {'run.stats.end_time': {'date': {'$eval': 'from_date'}}}}, {'lte': {'run.stats.end_time': {'date': {'$eval': 'to_date'}}}}]}, 'limit': 100, 'format': 'table'}

Query after update:
{'from': 'unittest', 'select': [{'aggregate': 'count'}], 'groupby': [{'value': 'result.test'}, {'value': 'run.suite.fullname'}], 'where': {'and': [{'eq': {'repo.branch.name': 'mozilla-central'}}, {'eq': {'result.status': 'SKIP'}}, {'gte': {'run.stats.end_time': {'date': {'$eval': 'from_date'}}}}, {'lte': {'run.stats.end_time': {'date': {'$eval': 'to_date'}}}}]}, 'limit': 100, 'format': 'table'}

Query after render:
{'from': 'unittest', 'select': [{'aggregate': 'count'}], 'groupby': [{'value': 'result.test'}, {'value': 'run.suite.fullname'}], 'where': {'and': [{'eq': {'repo.branch.name': 'mozilla-central'}}, {'eq': {'result.status': 'SKIP'}}, {'gte': {'run.stats.end_time': {'date': 'today-week'}}}, {'lte': {'run.stats.end_time': {'date': 'eod'}}}]}, 'limit': 100, 'format': 'table'}
 ```

**Comment by MadinaB** [comment]
`adr skipped_tests --from today-week --suite xpcshell --platform maxosx64`
```
optional_arguments:
['suite', 'platform']

Query before update:
{'from': 'unittest', 'select': [{'aggregate': 'count'}], 'groupby': [{'value': 'result.test'}, {'value': 'run.suite.fullname'}], 'where': {'and': [{'eq': {'run.suite.fullname': {'$eval': 'suite'}}}, {'eq': {'build.platform': {'$eval': 'platform'}}}, {'eq': {'repo.branch.name': 'mozilla-central'}}, {'eq': {'result.status': 'SKIP'}}, {'gte': {'run.stats.end_time': {'date': {'$eval': 'from_date'}}}}, {'lte': {'run.stats.end_time': {'date': {'$eval': 'to_date'}}}}]}, 'limit': 100, 'format': 'table'}

Query after update:
{'from': 'unittest', 'select': [{'aggregate': 'count'}], 'groupby': [{'value': 'result.test'}, {'value': 'run.suite.fullname'}], 'where': {'and': [{'eq': {'run.suite.fullname': {'$eval': 'suite'}}}, {'eq': {'build.platform': {'$eval': 'platform'}}}, {'eq': {'repo.branch.name': 'mozilla-central'}}, {'eq': {'result.status': 'SKIP'}}, {'gte': {'run.stats.end_time': {'date': {'$eval': 'from_date'}}}}, {'lte': {'run.stats.end_time': {'date': {'$eval': 'to_date'}}}}]}, 'limit': 100, 'format': 'table'}

Query after render:
{'from': 'unittest', 'select': [{'aggregate': 'count'}], 'groupby': [{'value': 'result.test'}, {'value': 'run.suite.fullname'}], 'where': {'and': [{'eq': {'run.suite.fullname': 'xpcshell'}}, {'eq': {'build.platform': 'maxosx64'}}, {'eq': {'repo.branch.name': 'mozilla-central'}}, {'eq': {'result.status': 'SKIP'}}, {'gte': {'run.stats.end_time': {'date': 'today-week'}}}, {'lte': {'run.stats.end_time': {'date': 'eod'}}}]}, 'limit': 100, 'format': 'table'}
```

**Comment by MadinaB** [comment]
```
def run_query(name, config, optional_arguments=[], **context):
    """Loads and runs the specified query, yielding the result.
    Given name of a query, this method will first read the query
    from a .query file corresponding to the name.
    After queries are loaded, each query to be run is inspected
    and overridden if the provided context has values for limit.
    The actual call to the ActiveData endpoint is encapsulated
    inside the query_activedata method.
    :param str name: name of the query file to be loaded.
    :param Configuration config: config object.
    :param dict context: dictionary of ActiveData configs.
    :yields str: json-formatted string.
    """
    for query in load_query(name):
        # If limit is in the context, override the queries' value. We do this
        # to keep the results down to a sane level when testing queries.
        if 'limit' in context:
            query['limit'] = context['limit']
        if 'format' in context:
            query['format'] = context['format']
        if config.debug:
            query['meta'] = {"save": True}
        print("optional_arguments:")
        print(optional_arguments)
        print()
        print("Query before update:")
        print(query)
        update_query(query, context, optional_arguments)
        print()
        print("Query after update:")
        print(query)
        query = jsone.render(query, context)
        print()
        print("Query after render:")
        print(query)
        query_str = json.dumps(query, indent=2, separators=(',', ':'))
        log.debug("Running query {}:\n{}".format(name, query_str))
        yield query_activedata(query_str, config.url)
```

**Comment by ahal** [comment]
Thanks for your work here! I believe this issue has been resolved another way (plus it has a lot of bitrot), so closing. Thanks for your understanding.

**Pull request closed without merging**
