### PR TITLE
Show single subtest across all perf suites

### PR DESCRIPTION
**Pull request by klahnakoski**

### CODE REVIEW

**Comment by klahnakoski** [comment]
image

**Comment by klahnakoski** [comment]
I assume you will merge this if it is good.

**Comment by davehunt** [comment]
This looks excellent, thanks @klahnakoski! One comment on the output is that we're planning to remove the redundancy of the test name from the subtest name in [bug 1520417](https://bugzilla.mozilla.org/show_bug.cgi?id=1520417). This change will make the output less clear, so I'm wondering if we can output the test name for each row and the shortened subtest name in the column header?

**Comment by klahnakoski** [comment]
@ahal   sorry I missed the automated checks.  ready for another review

**Comment by klahnakoski** [comment]
image

**Comment by ahal** [comment]
Turns out deleting that list exposes a bug, my apologies! I'll see if I can fix it myself before merging.

**Comment by ahal** [comment]
Ok this will be fixed in PR 117. I'll merge this after that other one lands.

**Pull request merged**
