### PR TITLE
show number of activedata requests by day

### PR DESCRIPTION
**Pull request by klahnakoski**

### CODE REVIEW

**Comment by klahnakoski** [comment]
This is a good example where a query can be run on it's own

**Comment by ahal** [comment]
Thanks, this looks good but I recently added a `doclint` linter that will fail travis if there is documentation missing.

Can you please add this to `docs/recipes.rst` as well as add a module-level docstring to the recipe file? You can take a look at other recipes to see an example. You'll need to rebase your changes on top of the latest master.

**Comment by klahnakoski** [comment]
I am not sure about the documentation magic, but I copied other recipes hoping it works.

**Comment by ahal** [comment]
Yeah, that should work. Fyi to run all the tests and linter's locally you can just run:
`tox` (you may need to pip install it first)

**Pull request merged**
