### PR TITLE
--help display fix

### PR DESCRIPTION
**Pull request by MadinaB**
Resolving bug in issue #55

### CODE REVIEW

**Comment by MadinaB** [comment]
screen shot 2018-10-30 at 1 07 44 pm

Hi @ahal,

I have actually solved the problem, but it resolves cases shown in demo image. What I mean it reacts not to 'adr recipe -- --help' , but 'adr recipe --help' and I assume this to be more pleasant behavior to treat --help as optional argument, rather than positional.

I will create PR for case 'adr recipe  --help'  now, and work creating PR for 'adr recipe -- --help'..

1st solution is very close to one you explained

**Comment by MadinaB** [comment]
Hello @ahal , I have tried to solve it and it works for 'adr <recipe> --help'. Thus, it treats --help now as an optional argument and conflicts with  'adr  --help' were avoided by adding 'conflict_handler='resolve'' on parser creations.

**Comment by ahal** [comment]
> Hello @ahal , I have tried to solve it and it works for `adr <recipe > --help`. Thus, it treats --help now as an optional argument and conflicts with 'adr --help' were avoided by adding 'conflict_handler='resolve'' on parser creations.

Thanks, I think you forgot to re-push your changes though!

**Comment by MadinaB** [comment]
It is a bit different since it uses not "-- -- help", but "--help", so I pushed with new PR since was not sure whether u will like this behavior. It is here: https://github.com/mozilla/active-data-recipes/pull/73

**Comment by ahal** [comment]
Oh, thanks! Let's close out this PR then.

**Pull request closed without merging**
