### PR TITLE
Modify run_query function (use args instead of **context)

### PR DESCRIPTION
**Pull request by TrangEmily**

### CODE REVIEW

**Comment by TrangEmily** [comment]
Hi @ahal The `extract_arguments(func, call, members=None)` will read `run` function and extract run contexts from attributes of first arguments (in this case, it is `args`)
  `root_func = root_node.body[0]
    # Get root args, only support first arg
    # TODO: support multiple args fetching
    root_arg = root_func.args.args[0].arg if len(root_func.args.args) > 0 else None`
Should we change the order of the arguments `run_query` instead?

**Comment by ahal** [comment]
Sure, the more important piece is that the order is consistent. Though couldn't `extract_arguments` just look at the second variable instead?

**Comment by TrangEmily** [comment]
Yes, I updated :-)

**Comment by ahal** [comment]
Thanks!

**Pull request merged**
